### PR TITLE
Bugfix/add destroy for dom leak

### PR DESCRIPTION
**Pull request by hata6502**

### CODE REVIEW

**Comment by Danue1** [comment]
I'm here.
Having plan to merge this PR?

**Review by neSpecc — APPROVED** [review]

**Comment by hata6502** [comment]
Thank you!

**Comment by hata6502** [comment]
Thank you for releasing a new version: v1.0.2
https://www.npmjs.com/package/codex-tooltip?activeTab=explore

**Comment by Danue1** [comment]
Good, good.
Thx!

**Comment by fyrepenguin** [comment]
When will this version of the package be added to editorjs?

**Comment by hata6502** [comment]
@fyrepenguin
Thank you!
I've forgot it.

**Pull request merged**
